# For general information about this file, check
# https://doc.rust-lang.org/stable/clippy/configuration.html

msrv = "1.63"

absolute-paths-allowed-crates = [ "clap" ]
doc-valid-idents = [
  "WebDriver",
  "..",
]
