[package]
name = "shave"
version = "0.0.0"
edition = "2021"
default-run = "shave"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "shell-complete"
path = "var/shell-complete.rs"
required-features = ["clap_complete"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
incremental = false
panic = "abort"

[build-dependencies]
anyhow = "1.0.68"
grev = "0.1.3"

[dependencies]
anyhow = { version = "1.0.80", default-features = false, features = ["std"] }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
clap = { version = "4.1.4", default-features = false, features = ["color", "derive", "error-context", "help", "std", "suggestions", "usage"] }
clap_complete = { version = "4.1.4", default-features = false, optional = true }
fantoccini = { version = "0.20.0-rc.7", default-features = false }
hyper = { version = "0.14", default-features = false, features = ["tcp"] }
libc = { version = "0.2", default-features = false }
serde_json = { version = "1.0.114", default-features = false, features = ["std"] }
tempfile = { version = "3.2", default-features = false }
tokio = { version = "1.0", default-features = false, features = ["fs", "io-std", "io-util", "macros", "process", "rt", "time"] }

[dev-dependencies]
tokio = { version = "1.0", default-features = false, features = ["test-util"] }
