name: Build shavecli

on:
  workflow_dispatch:

jobs:
  build:
    name: Build shavecli
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [
          x86_64-unknown-linux-musl,
        ]
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}
      - run: |
          CARGO_PROFILE_RELEASE_DEBUG=false CARGO_PROFILE_RELEASE_STRIP=true cargo install --path=cli --root=. --target ${{ matrix.target }}
      - uses: actions/upload-artifact@v4
        with:
          name: shavecli-${{ matrix.target }}
          path: bin/shavecli
